// Case文テスト
// 連続したcase文を含むテスト

func multiCaseTest() {
    let x = 5
    
    // 最初のマッチした条件が実行されるはず
    case x > 0:
        "正の数" >> 💩
    case x > -10:
        "これは実行されないはず" >> 💩
    case default:
        "デフォルトも実行されないはず" >> 💩
}

func noMatchTest() {
    let x = 5
    
    // どの条件もマッチしない場合、default が実行されるはず
    case x < 0:
        "負の数" >> 💩
    case x > 10:
        "10より大きい" >> 💩
    case default:
        "どれにも当てはまらないのでデフォルト" >> 💩
}

func noMatchNoDefaultTest() {
    let x = 5
    
    // どの条件もマッチせず、defaultもない場合は NULL が返されるはず
    case x < 0:
        "負の数" >> 💩
    case x > 10:
        "10より大きい" >> 💩
}

func errorContinueTest() {
    let x = 5
    
    // エラーになる条件は次のcaseに進むはず
    case undefined_var > 0:
        "エラーになるため表示されない" >> 💩
    case x > 0:
        "条件が真なので表示される" >> 💩
    case default:
        "エラー後にマッチするcaseがあるので表示されない" >> 💩
}

// テスト実行
"===== 複数のcase文のテスト ======" |> print
multiCaseTest() |> print

"===== いずれにもマッチしない場合のテスト ======" |> print
noMatchTest() |> print

"===== いずれにもマッチせずデフォルトもない場合のテスト ======" |> print
noMatchNoDefaultTest() |> print  // NULLが表示されるはず

"===== エラーを含むcase文の連鎖テスト ======" |> print
errorContinueTest() |> print
