// このファイルは意図的に構文エラーを含んでいます
// エラーになることを確認するためのテストケース

// 関数外でのcase文使用（エラーになるはず）
let x = 10
case x > 5:
  "This should fail" |> print
